syntax = "Lua51"
indent_width = 4
quote_style = "AutoPreferSingle"
call_parentheses = "NoSingleTable"
indent_type = "Spaces"

#column_width = 120
#line_endings = "Unix"
# collapse_simple_statement = "Never"
# space_after_function_names = "Never"
# block_newline_gaps = "Never"
